site_name: OlympiCode

theme:

  name: material 
  language: sh
  logo: assets/images/logo-icon.png
  favicon: assets/images/favicon.png
  palette:
    primary: custom
    accent: custom
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - content.code.copy
  custom_dir: overrides
  
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

extra:
  analytics:
    provider: google
    property: G-RQJ7SCHCH5
    feedback:
      title: Da li je stranica bila korisna?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Stranica je bila korisna
          data: 1
          note: >-
            Hvala vam na povratnoj informaciji!
        - icon: material/emoticon-sad-outline
          name: Stranica se može popraviti
          data: 0
          note: >- 
            Hvala vam na povratnoj informaciji! Pomozite nam da popravimo ovu stranicu popunjavanjem sledećeg <a href="..." target="_blank" rel="noopener">formulara</a>.

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css: 
  - stylesheets/style.css

plugins:
  - search
  - literate-nav:
      nav_file: nav.md
      tab_length: 2