site_name: OlympiCode

theme:

  name: material 
  language: sh
  logo: assets/logo-icon.png
  favicon: assets/favicon.png
  palette:
    primary: custom
    accent: custom
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - content.code.copy
  custom_dir: overrides
  
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

extra:
  analytics:
    provider: google
    property: G-RQJ7SCHCH5

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css: 
  - stylesheets/style.css
